In [1]:
from mtsoo import *
from slgep_lib.chromosome import *
import numpy as np
from copy import deepcopy


In [2]:
names = ['CartPole-v1','CartPole-v1']
envs = GymTaskSet(names)

max_arity = 2
h_main = 5
h_adf = 3
no_terminal = 4
no_main = 2
no_adf = 4
no_pop = 10
T = 2
pop = Slgep_pop(no_adf, no_terminal, no_main,h_main, max_arity, h_adf, no_pop, T)
pop.pop[0].gene

array([11,  3,  5,  9,  6, 16, 16, 17, 16, 15, 15,  4,  2,  0,  3,  0, 15,
       17, 16, 15, 16, 15,  3,  4,  7, 12, 13, 13, 13,  0,  0,  3, 13, 12,
       13, 13,  1,  3,  5, 12, 13, 12, 12,  2,  1,  5, 13, 13, 12, 13],
      dtype=int32)

In [3]:
gene = Chromosome(no_adf, no_terminal, no_main,h_main, max_arity, h_adf, T)

In [4]:
gene.chromosome_range

ChromosomeRange(R1=8, R2=12, R3=14, R4=18)

In [5]:
symbol_list = gene.function_set + gene.adf_set + gene.adf_terminal_set + gene.terminal_set

In [6]:
if 0:
    print("0 is true")
else :
    print ("0 is false")

0 is false


In [7]:
no_pop = len(pop.pop)
fc = []
for i in range(no_pop):
    agent = pop.pop[i]
    sf = agent.sf
    result = envs.run_env(sf, agent)
    agent.factorial_cost[sf] = result
    fc.append(agent.factorial_cost)
fc

[array([-26.,  inf]),
 array([-30.,  inf]),
 array([-14.,  inf]),
 array([ inf, -53.]),
 array([ inf, -50.]),
 array([-9., inf]),
 array([-21.,  inf]),
 array([ inf, -33.]),
 array([inf, -9.]),
 array([-10.,  inf])]

In [10]:
np.argsort(np.argsort(fc, axis=0), axis=0) + 1

array([[ 1,  5],
       [ 3,  6],
       [ 2,  7],
       [ 7,  4],
       [ 4,  8],
       [ 8,  1],
       [ 6,  9],
       [ 5, 10],
       [ 9,  2],
       [10,  3]])

In [9]:
np.min(np.argsort(np.argsort(fc, axis=0), axis=0) + 1, axis=1)

array([1, 3, 2, 4, 4, 1, 6, 5, 2, 3])

In [12]:
s_fitness = 1 / np.min(np.argsort(np.argsort(fc, axis=0), axis=0) + 1, axis=1)
s_fitness

array([1.        , 0.33333333, 0.5       , 0.25      , 0.25      ,
       1.        , 0.16666667, 0.2       , 0.5       , 0.33333333])

In [16]:
for i in range(no_pop):
    print(pop.pop[i].factorial_cost)

[-65.  inf]
[-10.  inf]
[-26.  inf]
[inf -9.]
[-10.  inf]
[ inf -12.]
[-9. inf]
[-10.  inf]
[ inf -12.]
[ inf -10.]


In [17]:
for i in range(no_pop):
    print(pop.pop[i].scalar_fitness)

1.0
0.3333333333333333
0.5
0.25
0.25
1.0
0.16666666666666666
0.2
0.5
0.3333333333333333


In [15]:
pop.evaluate(envs)

In [18]:
pop.sort()

In [19]:
for i in range(no_pop):
    print(pop.pop[i].factorial_cost)

[-65.  inf]
[ inf -12.]
[-26.  inf]
[ inf -12.]
[-10.  inf]
[ inf -10.]
[inf -9.]
[-10.  inf]
[-10.  inf]
[-9. inf]


In [20]:
for i in range(no_pop):
    print(pop.pop[i].scalar_fitness)

1.0
1.0
0.5
0.5
0.3333333333333333
0.3333333333333333
0.25
0.25
0.2
0.16666666666666666


In [67]:
pop.permute()

In [20]:
subpops = pop._get_subpops()
subpop = subpops[0]
subpop[0].D

50

In [21]:
test = pop.learn_rmp()

In [22]:
a = np.random.rand(2,6)
np.mean(a, axis=0)

array([0.53415073, 0.12109041, 0.46947723, 0.33498433, 0.86394847,
       0.60137323])

In [23]:
subgene = np.array([p.gene for p in subpop])
subgene[:,0]

array([ 5, 10,  8,  3,  5,  7,  2], dtype=int32)

In [24]:
norm.pdf(subgene[:,0], loc = 3, scale = 1)

array([5.39909665e-02, 9.13472041e-12, 1.48671951e-06, 3.98942280e-01,
       5.39909665e-02, 1.33830226e-04, 2.41970725e-01])

In [25]:
test

array([[1., 0.],
       [0., 1.]])

In [50]:
pl = np.arange(1,1+3)
parent = [pop.pop[i] for i in pl]
parent[1:4]

In [52]:
N= 10
K=2
skill_factor = np.array([i % K for i in range(2 * N)])

In [56]:
np.where(skill_factor ==1)

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),)

In [57]:
np.argmax([2,3,1,4,5])

4

In [69]:
top = max(enumerate(pop.pop), key = lambda x:x[1].scalar_fitness)
top

(1, <slgep_lib.chromosome.Chromosome at 0x7f3a62191580>)

In [21]:
p1 = pop.pop[1]
p2 = pop.pop[2]
x = np.random.randint(0,p1.D)
p1.gene[0:x]

array([ 4,  0,  7, 10,  7, 16, 14, 15, 14, 16, 15,  4,  2,  8, 11,  2, 14,
       17, 14, 17, 15, 16,  2,  4,  0, 12, 12, 13], dtype=int32)

In [31]:
no_terminal = envs.envs[0].reset().shape[0]
no_terminal

4

In [22]:
pop._get_best_individual_of_task(0)

(<slgep_lib.chromosome.Chromosome at 0x7f9fb4f517f0>, -65.0)

In [9]:
x = pop.pop[2]
best, _ = pop._get_best_individual_of_task(x.sf)
a, b = np.random.choice(pop.pop, 2)

In [39]:
vp = np.ones(x.D)
vp[np.where(x.gene == best.gene)] = 0
vp

array([1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1.])

In [41]:
l = []
m = []
for i in range(x.D):
    if x.gene[i]==best.gene[i]:
        l.append(i)
for i in range(x.D):
    if x.gene[i]!=best.gene[i]:
        m.append(i)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
vp[m]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [43]:
vp[l]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
for p in pop.pop:
    print(p.factorial_cost)

[-14.  inf]
[-10.  inf]
[-10.  inf]
[-12.  inf]
[-10.  inf]
[-17.  inf]
[-10.  inf]
[ inf -62.]
[-9. inf]
[-10.  inf]


In [8]:
pop.permute()

In [47]:
if []:
    print('is true')
else:
    print('is false')

is false


In [43]:
a.shape

(1, 3)

In [ ]:
def one_point_crossover_adf(self, pa, pb):
    D = len(pa)
    i = np.random.randint(low=1, high=D-1)
    low, high = self._get_crossover_range(i)
    ca = deepcopy(pa)
    cb = deepcopy(pa)
    if np.random.rand() < 0.5:
        ca[low:i] = pb[low:i]
        cb[low:i] = pa[low:i]
    else:
        ca[i:high] = pb[i:high]
        cb[i:high] = pa[i:high]
    return ca, cb


In [ ]:
def one_point_crossover_adf_multitask(self, pa, pb):
    D = len(pa)
    config = self.config
    low = config['num_main'] * (config['h_main'] + config['l_main'])
    i = np.random.randint(low=low + 1, high=D-1)
    low, high = self._get_crossover_range(i)
    ca = deepcopy(pa)
    cb = deepcopy(pa)
    if np.random.rand() < 0.5:
        ca[low:i] = pb[low:i]
        cb[low:i] = pa[low:i]
    else:
        ca[i:high] = pb[i:high]
        cb[i:high] = pa[i:high]
    return ca, cb

In [7]:
a = pop.pop[0]
a.gene

array([ 4, 10,  8,  1,  0, 14, 16, 16, 16, 16, 14,  0,  1,  3, 10, 10, 17,
       16, 17, 17, 14, 17,  1,  0,  4, 12, 12, 12, 12,  5,  2,  3, 13, 12,
       12, 13,  7,  0,  2, 12, 13, 12, 13,  1,  2,  6, 12, 13, 12, 12],
      dtype=int32)

In [8]:
pop.frequency_based_mutation(a,0.1)

In [9]:
pop.pop[0].D

50

In [8]:
1 + 1+ 1 +1 +2 +2 +2

10

In [53]:
a = np.array([1,2,3,4])
np.hstack([a, np.zeros(2)])

array([1., 2., 3., 4., 0., 0.])

In [8]:
x = pop.pop[0]
y = pop.pop[1]
z = pop.pop[2]
b1 = b2 = b3 = 0.5
m = deepcopy(x)
n = deepcopy(y)
p = deepcopy(z)


In [9]:
print(m.gene)
print(n.gene)
print(p.gene)

[11  3  5  9  6 16 16 17 16 15 15  4  2  0  3  0 15 17 16 15 16 15  3  4
  7 12 13 13 13  0  0  3 13 12 13 13  1  3  5 12 13 12 12  2  1  5 13 13
 12 13]
[ 0  5  4  4  9 14 16 15 15 16 17  2  4  3  5  0 15 14 14 14 14 17  3  4
  7 12 13 13 12  3  6  4 12 13 13 13  4  0  3 13 13 12 13  5  2  3 13 13
 12 12]
[ 6  3  9 10  7 14 14 16 16 16 16 11  5  0 11  0 17 17 17 14 14 14  1  3
  3 13 13 12 13  5  4  7 13 13 12 13  5  5  1 13 13 13 13  0  5  7 12 13
 13 12]


In [10]:
for i in range(x.D):
    m.gene[i] = x.gene[i] + b1*(y.gene[i]-z.gene[i])
    m.gene[i] = m._gene_rescale(i, b1)
#     m.gene[i] = y.gene[i] + b2*(z.gene[i]-x.gene[i])
#     m.gene[i] = m._gene_rescale(i, b1)
    
#     m.gene[i] = z.gene[i] + b2*(x.gene[i]-y.gene[i])
#     m.gene[i] = m._gene_rescale(i, b1)

8
7


4
5


2
4


6
6


7
6


16
16


17
16


16
16


15
16


15
16


15
16


0
3


1
4


1
4


0
3


0
3


14
15


15
16


14
15


15
16


16
16


16
16


4
4


4
4


9
6


11
12


13
13


13
13


12
12


-1
2


1
2


1
2


12
12


12
12


13
13


13
13


0
2


0
2


6
5


12
12


13
13


11
12


12
12


4
4


0
2


3
4


13
13


13
13


11
12


13
13




In [70]:
print(m.gene)
print(n.gene)
print(p.gene)

[ 8  5  6  7  5 15 15 15 16 15 14  5  1  3  3  3 16 15 16 15 15 14  3  2
  6 13 13 12 13  4  4  5 12 12 12 13  2  2  1 13 13 12 13  4  2  3 12 12
 12 12]
[10  7 11  0  0 17 14 14 17 16 15  9  0  0  1  1 14 14 17 15 15 14  7  1
  6 13 13 12 13  1  7  7 13 12 12 12  3  2  0 13 13 13 13  5  1  7 12 12
 13 13]
[ 6 10  8  0  1 17 17 16 15 15 16  1  9  4  3  3 14 15 15 14 14 17  6  6
  1 12 12 12 12  2  3  0 13 12 13 12  7  2  4 13 13 12 12  0  5  4 13 13
 12 12]


In [ ]:
OldRange = (OldMax - OldMin)  
NewRange = (NewMax - NewMin)  
NewValue = (((OldValue - OldMin) * NewRange) / OldRange) + NewMin